/*
VW_CITAS_PSICOLOGICAS	Consultar citas
VW_HISTORIAL_CLINICO	Consultar historiales
VW_ACTIVIDADES_GRUPALES	Consultar actividades
VW_REPORTE_PACIENTES	Reporte de pacientes
VW_ESTADISTICAS_PACIENTES	Estadísticas
VW_REPORTE_ACTIVIDADES	Reporte consolidado
VW_RESUMEN_DNOP
*/


CREATE OR REPLACE VIEW VW_CITAS_PSICOLOGICAS AS
SELECT
    C.ID_CITA,
    P.PRIMER_NOMBRE_PACIENTE || ' ' || P.PRIMER_APELLIDO_PACIENTE AS PACIENTE,
    PS.PRIMER_NOMBRE_PSICOLOGO || ' ' || PS.PRIMER_APELLIDO_PSICOLOGO AS PSICOLOGO,
    C.FECHA_CITA,
    TO_CHAR(C.HORA_INICIO,'HH24:MI') AS HORA_INICIO,
    TO_CHAR(C.HORA_FIN,'HH24:MI') AS HORA_FIN,
    C.ESTADO_CITA,
    C.MOTIVO_CITA
FROM CITA C
JOIN PACIENTE P
ON C.ID_PACIENTE=P.ID_PACIENTE
JOIN PSICOLOGO PS
ON C.ID_PSICOLOGO=PS.ID_PSICOLOGO;

CREATE OR REPLACE VIEW VW_HISTORIAL_CLINICO AS
SELECT
R.NUMERO_REGISTRO,
P.PRIMER_NOMBRE_PACIENTE||' '||
P.PRIMER_APELLIDO_PACIENTE PACIENTE,
PS.PRIMER_NOMBRE_PSICOLOGO||' '||
PS.PRIMER_APELLIDO_PSICOLOGO PSICOLOGO,
R.FECHA_ATENCION,
R.ESTADO_CLINICO,
R.DIAGNOSTICO,
R.OBSERVACIONES
FROM REGISTRO_MEDICO R
JOIN PACIENTE P
ON R.ID_PACIENTE=P.ID_PACIENTE
JOIN PSICOLOGO PS
ON R.ID_PSICOLOGO=PS.ID_PSICOLOGO;


CREATE OR REPLACE VIEW VW_ACTIVIDADES_GRUPALES AS
SELECT
A.ID_ACTIVIDAD,
A.NOMBRE_ACTIVIDAD,
PR.NOMBRE_PROGRAMA,
PS.PRIMER_NOMBRE_PSICOLOGO||' '||
PS.PRIMER_APELLIDO_PSICOLOGO PSICOLOGO,
A.FECHA_ACTIVIDAD,
A.LUGAR_ACTIVIDAD,
A.CANTIDAD_PARTICIPANTES,
A.ESTADO_ACTIVIDAD
FROM ACTIVIDAD_GRUPAL A
JOIN PROGRAMAS PR
ON A.ID_PROGRAMA=PR.ID_PROGRAMA
JOIN PSICOLOGO PS
ON A.ID_PSICOLOGO=PS.ID_PSICOLOGO;


CREATE OR REPLACE VIEW VW_REPORTE_PACIENTES AS
SELECT
ID_PACIENTE,
PRIMER_NOMBRE_PACIENTE||' '||
PRIMER_APELLIDO_PACIENTE PACIENTE,
SEXO,
SEDE,
ROL_PACIENTE,
ASEGURADO
FROM PACIENTE;

CREATE OR REPLACE VIEW VW_ESTADISTICAS_PACIENTES AS
SELECT
SEDE,
SEXO,
COUNT(*) TOTAL_PACIENTES
FROM PACIENTE
GROUP BY
SEDE,
SEXO;


CREATE OR REPLACE VIEW VW_REPORTE_ACTIVIDADES AS
SELECT
PR.NOMBRE_PROGRAMA,
COUNT(A.ID_ACTIVIDAD) TOTAL_ACTIVIDADES,
SUM(A.CANTIDAD_PARTICIPANTES) TOTAL_PARTICIPANTES
FROM PROGRAMAS PR
LEFT JOIN ACTIVIDAD_GRUPAL A
ON PR.ID_PROGRAMA=A.ID_PROGRAMA
GROUP BY PR.NOMBRE_PROGRAMA;


CREATE OR REPLACE VIEW VW_RESUMEN_DNOP AS
SELECT
(SELECT COUNT(*) FROM PACIENTE) TOTAL_PACIENTES,
(SELECT COUNT(*) FROM PSICOLOGO) TOTAL_PSICOLOGOS,
(SELECT COUNT(*) FROM CITA) TOTAL_CITAS,
(SELECT COUNT(*) FROM REGISTRO_MEDICO) TOTAL_REGISTROS,
(SELECT COUNT(*) FROM ACTIVIDAD_GRUPAL) TOTAL_ACTIVIDADES
FROM DUAL;
